### ISSUE TITLE
How can i get the sendowl wrapper for PHP 

### ISSUE THREAD

**Issue by usamamashkoor** [mjerwin/sendowl#2]
Hi
How can i get the sendowl wrapper for PHP i can only see composer.json and      readme.md files in your repository.
Thanks and Regards 
M.Usama Mashkoor

**Comment by mjerwin** [comment]
Hi usamamashkoor,

Sorry for the late reply.
I'm still working on this at the moment, check out the [develop branch](https://github.com/mjerwin/sendowl/tree/develop) for the latest updates :)

Let me know if you have any suggestions or feel free to send a pull request.

Matthew
